apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

generatorOptions:
  labels:
    grafana_dashboard: "1"
  disableNameSuffixHash: true
  annotations:
    strategy.spinnaker.io/versioned: 'false'

configMapGenerator:
  - name: aws
    files:
      - aws/ec2.json
      - aws/elasticache.json
      - aws/rds.json
      - aws/cdn.json
  - name: flux-cluster
    files:
      - flux/cluster.json
      - flux/control-plane.json
  #  - name: prometheus-remote-write
  #    files:
  #      - general/prometheus-remote-write.json