apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

generatorOptions:
  labels:
    grafana_dashboard: "1"
  disableNameSuffixHash: true
  annotations:
    strategy.spinnaker.io/versioned: 'false'

configMapGenerator:
  - name: aws
    files:
      - aws/ec2.json
      - aws/elasticache.json
      - aws/rds.json
      - aws/cdn.json
  - name: flux-cluster
    files:
      - flux/cluster.json
      - flux/control-plane.json
  - name: linkerd
    files:
      - linkerd/authority.json
      - linkerd/cronjob.json
      - linkerd/daemonset.json
      - linkerd/deployment.json
      - linkerd/grafana.json
      - linkerd/health.json
      - linkerd/job.json
      - linkerd/kubernetes.json
  - name: linkerd2
    files:
      - linkerd/multicluster.json
      - linkerd/namespace.json
      - linkerd/pod.json
      - linkerd/prometheus.json
      - linkerd/prometheus-benchmark.json
      - linkerd/replicaset.json
      - linkerd/replicationcontroller.json
      - linkerd/route.json
      - linkerd/service.json
      - linkerd/statefulset.json
      - linkerd/top-line.json

  #  - name: prometheus-remote-write
  #    files:
  #      - general/prometheus-remote-write.json