apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - devops

patchesStrategicMerge:
  - devops-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: aws-environment
    namespace: kube-system
    literals:
      - cluster_region="ap-south-1"
      - account_id="832807087073"
      - cluster_name="ch-monitoring-eks"
  - name: aws-environment
    namespace: logging
    literals:
      - cluster_region="ap-south-1"
      - account_id="832807087073"
      - cluster_name="ch-monitoring-eks"
      - log_bucket="true"

  - name: aws-environment
    namespace: istio-system
    literals:
      - cluster_region="ap-south-1"
      - account_id="832807087073"
      - cluster_name="ch-monitoring-eks"
