---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: tf
    linkerd.io/inject: enabled
  annotations:
    linkerd.io/inject: enabled
  name: tf

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: tf
  name: tf
  namespace: tf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: tf
  name: tf-reconciler
  namespace: tf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:tf:reconciler
- kind: ServiceAccount
  name: tf
  namespace: tf
---
apiVersion: v1
data:
  password: Z2hwX1FIWDYzV29TRzJrdk5zOUV5TDJ0OHMyZ3Z0QnFVbjAzOXRpZg==
  username: Z2l0
kind: Secret
metadata:
  name: tf
  namespace: tf
type: Opaque

