apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-downscaler
    version: v20.10.0
  name: kube-downscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-downscaler
  template:
    metadata:
      labels:
        application: kube-downscaler
        version: v20.10.0
    spec:
      serviceAccountName: kube-downscaler
      containers:
        - name: downscaler
          # see https://github.com/hjacobs/kube-downscaler/releases
          image: hjacobs/kube-downscaler:21.2.0
          args:
            - --interval=60
            - --debug
            - --include-resources=deployment
            - --include-resources=rollout
            - --include-resources=statefulset
            - --exclude-namespace=flux-system
          envFrom:
            - configMapRef:
                name: kube-downscaler
                optional: true
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000