apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - deployment.yaml
  - rbac.yaml
configMapGenerator:
  - name: kube-downscaler
    literals:
      - DEFAULT_UPTIME="Mon-Fri 08:30-21:00 Asia/Kolkata"
      - EXCLUDE_NAMESPACES="argo-rollouts"
      - EXCLUDE_DEPLOYMENTS="coredns,cluster-autoscaler,kube-downscaler"