apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kyverno/kyverno/v1.8.1-rc1/definitions/release/install.yaml
patchesStrategicMerge:
  - nodeSelectors.yaml
