apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
#  - https://raw.githubusercontent.com/kyverno/kyverno/v1.3.5/definitions/release/install.yaml
patchesStrategicMerge:
  - nodeSelectors.yaml