apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno
  namespace: kyverno
spec:
  template:
    spec:
      nodeSelector:
        workload: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists