apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: linkerd
spec:
  interval: 10m
  timeout: 5m
  path: "./kustomize/base/flagger"
  prune: true
  serviceAccountName: devops
  sourceRef:
    kind: GitRepository
    name: flagger
    namespace: linkerd
  targetNamespace: linkerd
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: flagger
      spec:
        template:
          spec:
            containers:
              - name: flagger
                args:
                  - -log-level=info
                  - -mesh-provider=linkerd
                  - -metrics-server=http://prometheus-operated.monitoring.svc.cluster.local:9090
    - apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: flagger
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: flagger
      subjects:
        - kind: ServiceAccount
          name: flagger
          namespace: linkerd

