---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: aws-load-balancer-controller
  serviceAccountName: devops
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flagger-system
  values:
    clusterName: services
    nodeSelector:
       workload: system