apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: eks
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 30m0s
  timeout: 10m
  releaseName: aws-load-balancer-controller
  serviceAccountName: devops
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
  values:
    syncPeriod: 30m0s
    clusterName: ${cluster_name}
    nodeSelector:
       workload: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    resources:
       limits:
         cpu: 300m
         memory: 256Mi
       requests:
         cpu: 100m
         memory: 128Mi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::${account_id}:role/load-balancer-${cluster_region}
    image:
      repository: 602401143452.dkr.ecr.${cluster_region}.amazonaws.com/amazon/aws-load-balancer-controller