apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: services
  region: ap-south-1
  version: "1.19"


vpc:
  id: "vpc-0e0ccffca59ba6525"
  cidr: "10.8.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      ap-south-1a:
        id: "subnet-00f7e0ce61b65419a"
        cidr: "10.8.0.0/19"
      ap-south-1b:
        id: "subnet-0b2d5546b6ed22566"
        cidr: "10.8.64.0/19"
    public:
      ap-south-1a:
        id: "subnet-048d248e611b48e23"
        cidr: "10.8.216.0/21"
      ap-south-1b:
        id: "subnet-0a3f7abd03caf8e2e"
        cidr: "10.8.224.0/21"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: aws-cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true

nodeGroups:
  - name: edge
    instanceType: "m5a.large"
    desiredCapacity: 0
    minSize: 0
    maxSize: 3
    volumeSize: 20
    volumeType: gp2
    volumeEncrypted: true
    volumeKmsKeyID: 97f38a15-a525-49d6-beb7-7e768066c762
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::832807087073:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::832807087073:role/EKS-Default-SSM-AD-Role
    labels:
      workload: public
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services-ap-south-1: "owned"

managedNodeGroups:
  - name: system
    instanceType: "t3.xlarge"
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    volumeSize: 20
    volumeType: gp3
    volumeEncrypted: true
    volumeKmsKeyID: 97f38a15-a525-49d6-beb7-7e768066c762
    privateNetworking: true
    disableIMDSv1: true
    iam:
      instanceRoleARN: arn:aws:iam::832807087073:role/EKS-Default-SSM-AD-Role
    labels:
      workload: system
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services-ap-south-1: "owned"

#fargateProfiles:
#  - name: fp-coredns
#    selectors:
#      - namespace: kube-system
#        labels:
#          k8s-app: kube-dns

cloudWatch:
  clusterLogging:
    enableTypes: [ "authenticator" ]

addons:
  - name: vpc-cni
