apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
spec:
  template:
    spec:
      nodeSelector:
        workload: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists