apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: ap-south-1
  version: "1.20"

vpc:
  id: "vpc-003978caf25a1d7ce"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      ap-south-1a:
        id: "subnet-090c9cf2f159f2cd2"
      ap-south-1b:
        id: "subnet-0c1ee00495e8fa8e2"
      ap-south-1c:
        id: "subnet-014228877d6c932a6"
    public:
      ap-south-1a:
        id: "subnet-03ad4d9406c822c9b"
      ap-south-1b:
        id: "subnet-0ea11e9a3ea1bf0a4"
      ap-south-1c:
        id: "subnet-0ca9b2d007b987baf"

iam:
  withOIDC: true
  fargatePodExecutionRolePermissionsBoundary: arn:aws:iam::755502957828:policy/Default-Boundary-Policy
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      roleName: load-balancer-ap-south-1
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      roleName: external-dns-ap-south-1
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      roleName: cluster-autoscaler-ap-south-1
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: ebs-csi-driver
        namespace: kube-system
      roleName: ebs-csi-driver-ap-south-1
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: terraform-sync-workspace
        namespace: kube-system
      roleName: terraform
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
    - metadata:
        name: kubernetes-external-secrets
        namespace: kube-system
      roleName: external-secrets
      attachPolicy:
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetResourcePolicy
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
              - secretsmanager:ListSecretVersionIds
              - ssm:GetParameter
            Resource:
              - "*"
    - metadata:
        name: kube-bench
        namespace: kube-system
      roleName: kube-bench-ap-south-1
      attachPolicy:
        Statement:
          - Effect: Allow
            Action:
              - securityhub:BatchImportFindings
            Resource:
              - "arn:aws:securityhub:us-east-1::product/aqua-security/kube-bench"

managedNodeGroups:
  - name: system-1201
    instanceType: "a1.xlarge"
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: a3456af4-c4de-4938-837d-86d5615d75d7
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    securityGroups:
      withLocal: false
    iam:
      instanceRoleARN: arn:aws:iam::755502957828:role/EKS-Default-SSM-AD-Role
    labels:
      workload: system
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dev: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: system
      k8s.io/cluster-autoscaler/node-template/taint/CriticalAddonsOnly: NoSchedule
    taints:
      - key: CriticalAddonsOnly
        value: "true"
        effect: "NoSchedule"
    ssh:
      allow: true
      publicKeyName: bottlerocket
  - name: monitoring-1203
    spot: true
    instanceTypes: [ "r6g.large", "m6g.large", "t4g.large" ]
    availabilityZones:
    - ap-south-1a
    desiredCapacity: 1
    minSize: 0
    maxSize: 2
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: a3456af4-c4de-4938-837d-86d5615d75d7
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    securityGroups:
      withLocal: false
    iam:
      instanceRoleARN: arn:aws:iam::755502957828:role/EKS-Default-SSM-AD-Role
    labels:
      workload: monitoring
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dev: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: monitoring
      k8s.io/cluster-autoscaler/node-template/taint/monitoring: NoSchedule
    taints:
      - key: monitoring
        value: "true"
        effect: "NoSchedule"
  - name: gpu-compute-1203
    spot: true
    instanceTypes: [ "g4dn.xlarge", "g4dn.2xlarge" ]
    desiredCapacity: 0
    minSize: 0
    maxSize: 5
    volumeType: gp3
    volumeSize: 125
    volumeEncrypted: true
    volumeKmsKeyID: a3456af4-c4de-4938-837d-86d5615d75d7
    privateNetworking: true
    disableIMDSv1: true
    securityGroups:
      withLocal: false
      attachIDs:
        - sg-0f2067cc2e5c0240a
    iam:
      instanceRoleARN: arn:aws:iam::755502957828:role/EKS-Default-SSM-AD-Role
    labels:
      compute: gpu
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dev: "owned"
      k8s.io/cluster-autoscaler/node-template/label/compute: gpu
      k8s.io/cluster-autoscaler/node-template/taint/dld: NoSchedule
    taints:
      - key: dld
        value: "true"
        effect: "NoSchedule"
  - name: common-1203
    spot: true
    instanceTypes: [ "c4.4xlarge","c5.4xlarge", "c5a.4xlarge", "c5n.4xlarge", "m5a.4xlarge", "m5.4xlarge" ]
    availabilityZones:
      - ap-south-1a
    desiredCapacity: 1
    minSize: 0
    maxSize: 20
    volumeType: gp3
    volumeSize: 50
    volumeEncrypted: true
    volumeKmsKeyID: a3456af4-c4de-4938-837d-86d5615d75d7
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    securityGroups:
      withLocal: false
      attachIDs:
        - sg-0f2067cc2e5c0240a
    iam:
      instanceRoleARN: arn:aws:iam::755502957828:role/EKS-Default-SSM-AD-Role
    labels:
      workload: public
      falco: enabled
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/dev: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: public

cloudWatch:
  clusterLogging:
    enableTypes: [ "authenticator" ]

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

gitops:
  flux:
    gitProvider: github
    flags:
      owner: nslhb
      repository: services.nslhub.com
      branch: main
      namespace: flux-system
      path: ./clusters/dev/ap-south-1
      toleration-keys: CriticalAddonsOnly
      components-extra: "image-reflector-controller,image-automation-controller"
