apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo
  namespace: apps
spec:
  interval: 1m
  url: https://github.com/nslhb/services.nslhub.com.git
  ref:
    branch: apps
  secretRef:
    name: flux-system
  timeout: 20s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demo
  namespace: apps
spec:
  serviceAccountName: demo
  interval: 1m
  path: ./demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo
  validation: client
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    strategy: Setters