apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: paas
  namespace: paas
spec:
  ref:
    branch: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paas
  namespace: paas
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "901688089596"
      env: "prod"