apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: t360
  namespace: t360
spec:
  ref:
    branch: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: t360
  namespace: t360
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "901688089596"
      env: "prod"
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
  name: t360
