apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: services
  region: us-east-1
  version: "1.19"

vpc:
  id: "vpc-0d9e76bd7b471527d"
  cidr: "10.18.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      us-east-1a:
        id: "subnet-047a38909122b2903"
        cidr: "10.18.64.0/19"
      us-east-1d:
        id: "subnet-0df9cd915982e1d92"
        cidr: "10.18.0.0/19"
    public:
      us-east-1a:
        id: "subnet-0949343196a07f6c1"
        cidr: "10.18.224.0/21"
      us-east-1d:
        id: "subnet-0df685203f1522e82"
        cidr: "10.18.216.0/21"

kubernetesNetworkConfig:
  serviceIPv4CIDR: "172.18.0.0/16"

iam:
  withOIDC: true
  fargatePodExecutionRolePermissionsBoundary: arn:aws:iam::832807087073:policy/Default-Boundary-Policy
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      roleName: load-balancer-us-east-1
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      roleName: external-dns-us-east-1
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      roleName: cluster-autoscaler-us-east-1
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: ebs-csi-driver
        namespace: kube-system
      roleName: ebs-csi-driver-us-east-1
      wellKnownPolicies:
        ebsCSIController: true
nodeGroups:
  - name: system
    instanceType: "a1.xlarge"
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: fc0e8723-fa6e-4d9c-bd92-02c0e77886d4
    privateNetworking: true
    amiFamily: Bottlerocket
    ami: auto-ssm
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::832807087073:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::832807087073:role/EKS-Default-SSM-AD-Role
    labels:
      workload: system
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: system
      k8s.io/cluster-autoscaler/node-template/taint/CriticalAddonsOnly: NoSchedule
    taints:
      CriticalAddonsOnly: "true:NoSchedule"
    ssh:
      allow: true
      publicKeyName: bottlerocketkey
  - name: linkerd
    instanceType: "c6g.large"
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: fc0e8723-fa6e-4d9c-bd92-02c0e77886d4
    privateNetworking: true
    amiFamily: Bottlerocket
    ami: auto-ssm
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::832807087073:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::832807087073:role/EKS-Default-SSM-AD-Role
    labels:
      part-of: Linkerd
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/part-of: Linkerd
      k8s.io/cluster-autoscaler/node-template/taint/linkerd: NoSchedule
    taints:
      linkerd: "true:NoSchedule"
  - name: monitoring
    instanceType: "r6g.large"
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: fc0e8723-fa6e-4d9c-bd92-02c0e77886d4
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::832807087073:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::832807087073:role/EKS-Default-SSM-AD-Role
    labels:
      workload: monitoring
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: monitoring
      k8s.io/cluster-autoscaler/node-template/taint/monitoring: NoSchedule
    taints:
      monitoring: "true:NoSchedule"
  - name: edge
    instanceType: "t4g.medium"
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: fc0e8723-fa6e-4d9c-bd92-02c0e77886d4
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::832807087073:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::832807087073:role/EKS-Default-SSM-AD-Role
    labels:
      workload: public
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: public
      k8s.io/cluster-autoscaler/node-template/taint/Edge: NoSchedule
    taints:
      Edge: "true:NoSchedule"

# removed fargate profiles since they are running costlier
#fargateProfiles:
#  - name: coredns
#    selectors:
#      - namespace: kube-system
#        labels:
#          eks.amazonaws.com/component: coredns
#          k8s-app: kube-dns
#  - name: kube-downscaler
#    selectors:
#      - namespace: kube-system
#        labels:
#          application: kube-downscaler

cloudWatch:
  clusterLogging:
    enableTypes: [ "authenticator" ]

addons:
  - name: vpc-cni
