---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: keycloak
  annotations:
    linkerd.io/inject: enabled
  name: keycloak

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: keycloak
  name: keycloak
  namespace: keycloak

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    linkerd.io/inject: enabled
    toolkit.fluxcd.io/tenant: keycloak
  name: keycloak-reconciler
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:keycloak:reconciler
- kind: ServiceAccount
  name: keycloak
  namespace: keycloak

