apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/aws-ebs-csi-driver//deploy/kubernetes/overlays/stable/kustomization.yaml
  - storage-class.yaml
patchesStrategicMerge:
  - patch.yaml

images:
  - name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
    newTag: latest