apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::832807087073:role/ebs-csi-driver-ap-south-1
  name: ebs-csi-controller-sa
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    spec:
      tolerations:
        - key: SystemAddonsOnly
          operator: Exists
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebs-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      tolerations:
        - operator: Exists
---

