apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: aws-ebs-csi-driver
  serviceAccountName: devops
  chart:
    spec:
      chart: aws-ebs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
  values:
    nodeSelector:
      workload: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    node:
      tolerateAllTaints: true
    serviceAccount:
      controller:
        create: false
        name: ebs-csi-driver
      snapshot:
        create: false
        name: ebs-csi-driver
      node:
        create: false
        name: ebs-csi-driver
    enableVolumeResizing: true
    enableVolumeSnapshot: false
    resources:
       limits:
         cpu: 50m
         memory: 50Mi
       requests:
         cpu: 10m
         memory: 20Mi
    extraCreateMetadata: true
    k8sTagClusterId: "{cluster_name}"
    storageClasses:
     - name: ebs-sc
       annotations:
         storageclass.kubernetes.io/is-default-class: "true"
       volumeBindingMode: WaitForFirstConsumer
       parameters:
         encrypted: "true"
