apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged
spec:
  rules:
    - name: validate-privileged
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - monitoring
      validate:
        message: "Privileged mode is not allowed. Set privileged to false"
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(privileged): false
    - name: validate-allowPrivilegeEscalation
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - monitoring
      validate:
        message: "Privileged mode is not allowed. Set allowPrivilegeEscalation to false"
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
