apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m0s
  releaseName: kube-prometheus-stack
  serviceAccountName: devops
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
#    nodeExporter:
#      serviceMonitor:
#        relabelings:
#        - sourceLabels: [__meta_kubernetes_pod_node_name]
#          targetLabel: instance