apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rabbit-MQ
  namespace: rabbit-MQ
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: rabbit-MQ
  url: https://github.com/nslhb/gitops-paas.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rabbit-MQ
  namespace: rabbit-MQ
spec:
  interval: 1m
  path: ./
  prune: true
  serviceAccountName: rabbit-MQ
  sourceRef:
    kind: GitRepository
    name: rabbit-MQ
  validation: client