apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dld
  namespace: dld
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: dld
  url: https://github.com/nslhb/gitops-dld.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dld
  namespace: dld
spec:
  interval: 1m
  path: ./
  prune: true
  serviceAccountName: dld
  sourceRef:
    kind: GitRepository
    name: dld
  validation: client
  postBuild:
    substituteFrom:
      - kind: Secret
        name: aws-environment