apiVersion: v1beta1
kind: Bee
metadata:
  name: bee
spec:
  action: fly
---
apiVersion: jingfang.example.com/v1beta1
kind: MyKind
metadata:
  name: mykind
spec:
  secretRef:
    name: crdsecret
    zap: crdsecret
  beeRef:
    name: bee
    action: $(BEE_ACTION)
  containers:
  - command:
    - "echo"
    - "$(BEE_ACTION)"
    image: myapp
