apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ailabs
  namespace: ailabs
spec:
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ailabs
  namespace: ailabs
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "755502957828"
      env: "dev"