apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ava-nlg
  namespace: ava-nlg
spec:
  ref:
    branch: dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ava-nlg
  namespace: ava-nlg
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "755502957828"
      env: "dev"
