apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../teams/devops
  - ../../teams/paas
  - ../../teams/tf
  - ../../teams/avanlg
  - ../../teams/taas
  - ../../teams/dld
  - secrets.yaml
patchesStrategicMerge:
  - devops-patch.yaml
  - paas-patch.yaml
  - tf-patch.yaml
  - taas-patch.yaml
  - avanlg-patch.yaml
  - dld-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: aws-environment
    namespace: kube-system
    literals:
      - cluster_region="ap-south-1"
      - account_id="755502957828"
      - cluster_name="dev"
  - name: aws-environment
    namespace: logging
    literals:
      - cluster_region="ap-south-1"
      - account_id="755502957828"
      - cluster_name="dev"
      - log_bucket="false"
  - name: aws-environment
    namespace: istio-system
    literals:
      - cluster_region="ap-south-1"
      - account_id="755502957828"
      - cluster_name="dev"
secretGenerator:
  - name: aws-environment
    namespace: kube-system
    literals:
      - TEST=demo
      - cluster_region="ap-south-1"
      - account_id="755502957828"
      - cluster_name="dev"
