apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../teams/devops
  - ../../teams/paas
  - ../../teams/devops/linkerd.yaml
  - ../../teams/devops/ecr-sync.yaml
patchesStrategicMerge:
  - devops-patch.yaml
  - paas-patch.yaml