apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../teams/devops
  - ../../teams/paas
  - ../../teams/tf
  - ecr-sync.yaml
patchesStrategicMerge:
  - devops-patch.yaml
  - paas-patch.yaml
  - tf-patch.yaml