apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: paas
  namespace: paas
spec:
  ref:
    branch: dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paas
  namespace: paas
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "832807087073"
      env: "dev"