apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
<<<<<<< HEAD
  name: taas
  namespace: taas
=======
  name: tf
  namespace: tf
>>>>>>> 6670ef72592d2c02ba08170352c7df36edeccf00
spec:
  ref:
    branch: dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
<<<<<<< HEAD
  name: taas
  namespace: taas
=======
  name: tf
  namespace: tf
>>>>>>> 6670ef72592d2c02ba08170352c7df36edeccf00
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "832807087073"
      env: "dev"