apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: rollouts-demo
  metrics:
    - name: success-rate
      interval: 5m
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
          query: |
            sum(irate(
              route_response_total{job="linkerd-proxy",app=~"{{args.service-name}}", dst=~"(.*)elb.amazonaws.com(.*)", response_code!~"5.*"}[5m]
            )) /
            sum(irate(
              route_response_total{job="linkerd-proxy",app=~"{{args.service-name}}",  dst=~"(.*)elb.amazonaws.com(.*)"}[5m]
            ))