apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 10m0s
  releaseName: linkerd
  serviceAccountName: devops
  targetNamespace: linkerd
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM
  values:
    installNamespace: false
    identity:
      issuer:
        crtExpiry: "2022-04-04T22:52:03Z"
    controlPlaneTracing: true
    controlPlaneTracingNamespace: linkerd-jaeger
    tolerations:
      - key: linkerd
        operator: Exists
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
#    - name: jaeger
#      namespace: linkerd
    - name: linkerd
      namespace: linkerd
  interval: 10m0s
  releaseName: linkerd-viz
  serviceAccountName: devops
  targetNamespace: flux-system
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  values:
    grafana:
      enabled: false
    grafanaUrl: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000
#    jaegerUrl: http://jaeger.linkerd-jaeger.svc.cluster.local:16686
    prometheus:
      enabled: false
    prometheusUrl: http://prometheus-operated.monitoring.svc.cluster.local:9090
    tolerations:
      - key: linkerd
        operator: Exists
