apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1m
  path: ./keycloak2
  prune: true
  serviceAccountName: keycloak
  sourceRef:
    kind: GitRepository
    name: paas
    namespace: paas
  validation: client