apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secrets
  namespace: paas
spec:
  controller: default
  provider:
    aws:
      service: SecretsManager
      region: ${cluster_region}

---

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cdm-pg-credentials
  namespace: paas
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secrets
    kind: ClusterSecretStore
  target:
    name: cdm-pg-credentials
    creationPolicy: Owner
  data:
    - secretKey: cdm-pg-adminuser
      remoteRef:
        key: paas/tfnsl/workspace/postgres
        property: postgres_admin_user
    - secretKey: cdm-pg-password
      remoteRef:
        key: paas/tfnsl/workspace/postgres
        property: postgres_admin_pass