apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secrets
  namespace: paas
spec:
  controller: default
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1

---

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: pgsecrets
  namespace: paas
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secrets
    kind: ClusterSecretStore
  target:
    name: pgsecrets
    creationPolicy: Owner
  data:
    - secretKey: pgadminuser
      remoteRef:
        key: tfnsl/workspace
        property: postgres_admin_user
    - secretKey: pgpassword
      remoteRef:
        key: tfnsl/workspace
        property: postgres_admin_pass