apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: paas
  namespace: paas
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: paas
  url: ssh://git@github.com/nslhb/gitops-paas
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paas
  namespace: paas
spec:
  interval: 1m
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: paas
  validation: client

---
