apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: data
  namespace: paas
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: paas
  url: ssh://git@github.com/nslhb/gitops-paas
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paas-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/dev/ap-south-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

---
