apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: paas
  namespace: paas
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: paas
  url: https://github.com/nslhb/gitops-paas.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: paas
  namespace: paas
spec:
  interval: 1m
  path: ./
  prune: true
  serviceAccountName: paas
  sourceRef:
    kind: GitRepository
    name: paas
  validation: client
