apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 10m0s
  releaseName: falco
  serviceAccountName: devops
  targetNamespace: kube-system
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  values:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: Edge
        operator: Exists