apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  images:
    - name: argoproj/rollouts-demo
      newName: 832807087073.dkr.ecr.ap-south-1.amazonaws.com/rollouts-demo
      newTag: green # {"$imagepolicy": "flux-system:podinfo:tag"}
