apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::832807087073:role/eksctl-services-addon-iamserviceaccount-kube-Role1-1NTP8GKFPJIOW
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eks.amazonaws.com/role-arn: arn:aws:iam::832807087073:role/eksctl-services-addon-iamserviceaccount-kube-Role1-V63CL5UFWOJN
  name: aws-cluster-autoscaler
  namespace: kube-system