apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-multi-tenancy
spec:
  validationFailureAction: enforce
  rules:
    - name: serviceAccountName
      exclude:
        resources:
          namespaces:
            - flux-system
      match:
        resources:
          kinds:
            - Kustomization
            - HelmRelease
      validate:
        message: ".spec.serviceAccountName is required"
        pattern:
          spec:
            serviceAccountName: "?*"
    - name: sourceRefNamespace-devops
      exclude:
        resources:
          namespaces:
            - flux-system
      match:
        resources:
          namespaceSelector:
            matchLabels:
              toolkit.fluxcd.io/tenant: devops
          kinds:
            - Kustomization
      validate:
        message: "spec.sourceRef.namespace must be flux-system to avoid repetition"
        deny:
          conditions:
            - key: "{{request.object.spec.sourceRef.namespace}}"
              operator: NotEquals
              value: "flux-system"
    - name: helmRefNamespace-devops
      exclude:
        resources:
          namespaces:
            - flux-system
            - observability
      match:
        resources:
          namespaceSelector:
            matchLabels:
              toolkit.fluxcd.io/tenant: devops
          kinds:
            - HelmRelease
      validate:
        message: "spec.sourceRef.namespace must be flux-system to avoid repetition"
        deny:
          conditions:
            - key: "{{request.object.spec.chart.spec.sourceRef.namespace}}"
              operator: NotEquals
              value: "flux-system"
            - key: "{{request.object.spec.chart.spec.sourceRef.namespace}}"
              operator: NotEquals
              value: "observability"
    - name: sourceRefNamespace
      exclude:
        resources:
          namespaces:
            - flux-system
          namespaceSelector:
            matchLabels:
              toolkit.fluxcd.io/tenant: devops
      match:
        resources:
          kinds:
            - Kustomization
      validate:
        message: "spec.sourceRef.namespace must be the same as metadata.namespace"
        deny:
          conditions:
            - key: "{{request.object.spec.sourceRef.namespace}}"
              operator: NotEquals
              value: "{{request.object.metadata.namespace}}"
            - name: helmRefNamespace
              exclude:
                resources:
                  namespaces:
                    - flux-system
                  namespaceSelector:
                    matchLabels:
                      toolkit.fluxcd.io/tenant: devops
              match:
                resources:
                  kinds:
                    - HelmRelease
              validate:
                message: "spec.sourceRef.namespace must be the same as metadata.namespace"
                deny:
                  conditions:
                    - key: "{{request.object.spec.chart.spec.sourceRef.namespace}}"
                      operator: NotEquals
                      value: "{{request.object.metadata.namespace}}"
