---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: taas
    linkerd.io/inject: enabled
  annotations:
    linkerd.io/inject: enabled
  name: taas

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: taas
  name: taas
  namespace: taas

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: taas
  name: taas-reconciler
  namespace: taas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
<<<<<<< HEAD
  name: gotk:taas:reconciler
=======
  name: gotk:tf:reconciler
>>>>>>> 6670ef72592d2c02ba08170352c7df36edeccf00
- kind: ServiceAccount
  name: taas
  namespace: taas
---
apiVersion: v1
data:
  password: Z2hwX1FIWDYzV29TRzJrdk5zOUV5TDJ0OHMyZ3Z0QnFVbjAzOXRpZg==
  username: Z2l0
kind: Secret
metadata:
  name: taas
  namespace: taas
type: Opaque

