apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/falcosecurity
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---