---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/argo-rollouts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
  serviceAccountName: devops
  healthChecks:
    - kind: Deployment
      name: argo-rollouts
      namespace: argo-rollouts

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
  serviceAccountName: devops
  healthChecks:
    - kind: Deployment
      name: cluster-autoscaler
      namespace: kube-system
    - kind: Deployment
      name: aws-load-balancer-controller
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/linkerd
  prune: true
  serviceAccountName: devops
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
  healthChecks:
    - kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  validation: client
  serviceAccountName: devops
