apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "832807087073"
      cluster_name: "services"
  patchesStrategicMerge:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: csi-secrets-store
      namespace: flux-system
    values:
      tolerations:
        - key: Edge
          operator: Exists


---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  patchesStrategicMerge:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: kube-prometheus-stack
        namespace: monitoring
      spec:
        values:
          grafana:
            enabled: true
            ingress:
              enabled: true
              annotations:
                alb.ingress.kubernetes.io/group.name: default
                alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
                alb.ingress.kubernetes.io/scheme: internet-facing
                alb.ingress.kubernetes.io/target-type: ip
              hosts:
                - grafana.nslhub.click
              path: /*