apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../teams/devops
  - ../../teams/demo
  - linkerd.yaml
patchesStrategicMerge:
  - devops-patch.yaml
  - demo-patch.yaml
images:
  - name: ghcr.io/nslhb/rollouts-demo
    newTag: green # {"$imagepolicy": "apps:rollouts-demo:tag"}