apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../teams/devops
  - ../../teams/demo
  - ../_com
  - grafana-dashboards.yaml
patchesStrategicMerge:
  - devops-patch.yaml
  - demo-patch.yaml