---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  releaseName: metrics-server
  chart:
    repository: https://charts.helm.sh/stable
    name: metrics-server
    version: 2.11.4
  values:
    args:
      - --kubelet-preferred-address-types=InternalIP
    nodeSelector:
      workload: system