apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h0m0s
  timeout: 10m
  releaseName: kube-prometheus-stack
  serviceAccountName: devops
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheusOperator:
      admissionWebhooks:
        patch:
          tolerations:
            - key: monitoring
              operator: Exists
      tolerations:
        - key: monitoring
          operator: Exists
    prometheus-node-exporter:
      nodeSelector:
        eks.amazonaws.com/compute-type: ec2
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      tolerations:
        - key: monitoring
          operator: Exists
    kube-state-metrics:
      tolerations:
        - key: monitoring
          operator: Exists
    alertmanager:
      alertmanagerSpec:
        tolerations:
          - key: monitoring
            operator: Exists
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 8Gi
          limits:
            memory: 8Gi
        tolerations:
          - key: monitoring
            operator: Exists
        additionalScrapeConfigs:
          - job_name: kubernetes-apiserver
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - default
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: kubernetes;https
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: keep
                regex: true
                source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scrape
              - action: replace
                regex: (.+)
                source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_path
                target_label: __metrics_path__
              - action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                source_labels:
                  - __address__
                  - __meta_kubernetes_pod_annotation_prometheus_io_port
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: kubernetes_namespace
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: kubernetes_pod_name