apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m0s
  timeout: 10m
  releaseName: kube-prometheus-stack
  serviceAccountName: devops
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheusOperator:
      admissionWebhooks:
        patch:
          tolerations:
            - key: monitoring
              operator: Exists
      tolerations:
        - key: monitoring
          operator: Exists
    prometheus-node-exporter:
      nodeSelector:
        eks.amazonaws.com/compute-type: ec2
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      tolerations:
        - key: monitoring
          operator: Exists
    kube-state-metrics:
      tolerations:
        - key: monitoring
          operator: Exists
    alertmanager:
      alertmanagerSpec:
        tolerations:
          - key: monitoring
            operator: Exists
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 8Gi
          limits:
            memory: 8Gi
        tolerations:
          - key: monitoring
            operator: Exists
        additionalScrapeConfigs:
          - job_name: 'linkerd-controller'
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - 'linkerd'
                    - 'linkerd-viz'
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_container_port_name
                action: keep
                regex: admin-http
              - source_labels: [ __meta_kubernetes_pod_container_name ]
                action: replace
                target_label: component
          - job_name: 'linkerd-service-mirror'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_label_linkerd_io_control_plane_component
                  - __meta_kubernetes_pod_container_port_name
                action: keep
                regex: linkerd-service-mirror;admin-http$
              - source_labels: [ __meta_kubernetes_pod_container_name ]
                action: replace
                target_label: component
          - job_name: 'linkerd-proxy'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                  - __meta_kubernetes_pod_container_port_name
                  - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
                action: keep
                regex: ^{{default .Values.proxyContainerName "linkerd-proxy" .Values.proxyContainerName}};linkerd-admin;linkerd$
              - source_labels: [ __meta_kubernetes_namespace ]
                action: replace
                target_label: namespace
              - source_labels: [ __meta_kubernetes_pod_name ]
                action: replace
                target_label: pod
              # special case k8s' "job" label, to not interfere with prometheus' "job"
              # label
              # __meta_kubernetes_pod_label_linkerd_io_proxy_job=foo =>
              # k8s_job=foo
              - source_labels: [ __meta_kubernetes_pod_label_linkerd_io_proxy_job ]
                action: replace
                target_label: k8s_job
              # drop __meta_kubernetes_pod_label_linkerd_io_proxy_job
              - action: labeldrop
                regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
              # __meta_kubernetes_pod_label_linkerd_io_proxy_deployment=foo =>
              # deployment=foo
              - action: labelmap
                regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
              # drop all labels that we just made copies of in the previous labelmap
              - action: labeldrop
                regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
              # __meta_kubernetes_pod_label_linkerd_io_foo=bar =>
              # foo=bar
              - action: labelmap
                regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
              # Copy all pod labels to tmp labels
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
                replacement: __tmp_pod_label_$1
              # Take `linkerd_io_` prefixed labels and copy them without the prefix
              - action: labelmap
                regex: __tmp_pod_label_linkerd_io_(.+)
                replacement: __tmp_pod_label_$1
              # Drop the `linkerd_io_` originals
              - action: labeldrop
                regex: __tmp_pod_label_linkerd_io_(.+)
              # Copy tmp labels into real labels
              - action: labelmap
                regex: __tmp_pod_label_(.+)
          - job_name: kubernetes-apiserver
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - default
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: kubernetes;https
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: keep
                regex: true
                source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scrape
              - action: replace
                regex: (.+)
                source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_path
                target_label: __metrics_path__
              - action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                source_labels:
                  - __address__
                  - __meta_kubernetes_pod_annotation_prometheus_io_port
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: kubernetes_namespace
              - action: replace
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: kubernetes_pod_name