apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rbac.yaml
- linkerd/linkerd-certs.yaml
- linkerd/linkerd-release.yaml
- linkerd/linkerd-repository.yaml
- flagger/flagger-kustomization.yaml
- flagger/flagger-repository.yaml
- kubernetes-dashboard
- monitoring/prometheus-operator.yaml
- kube-system.yaml
