apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: services
  region: ap-south-1
  version: "1.19"

vpc:
  id: "vpc-003978caf25a1d7ce"
  cidr: "10.100.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      ap-south-1a:
        id: "subnet-090c9cf2f159f2cd2"
        cidr: "10.100.0.0/19"
      ap-south-1b:
        id: "subnet-0c1ee00495e8fa8e2"
        cidr: "10.100.64.0/19"
      ap-south-1c:
        id: "subnet-014228877d6c932a6"
        cidr: "10.100.128.0/19"
    public:
      ap-south-1a:
        id: "subnet-03ad4d9406c822c9b"
        cidr: "10.100.216.0/21"
      ap-south-1b:
        id: "subnet-0ea11e9a3ea1bf0a4"
        cidr: "10.100.224.0/21"
      ap-south-1c:
        id: "subnet-0ca9b2d007b987baf"
        cidr: "10.100.232.0/21"
iam:
  withOIDC: true
  fargatePodExecutionRolePermissionsBoundary: arn:aws:iam::755502957828:policy/Default-Boundary-Policy
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      roleName: load-balancer-ap-south-1
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      roleName: external-dns-ap-south-1
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      roleName: cluster-autoscaler-ap-south-1
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: kube-prometheus-stack-grafana
        namespace: monitoring
        labels: {aws-usage: "application"}
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess"
      roleName: cloudwatch-ap-south-1
    - metadata:
        name: ebs-csi-driver
        namespace: kube-system
      attachPolicy:
        Statement:
          - Effect: Allow
            Action:
              - ec2:AttachVolume
              - ec2:CreateSnapshot
              - ec2:CreateTags
              - ec2:CreateVolume
              - ec2:DeleteSnapshot
              - ec2:DeleteTags
              - ec2:DeleteVolume
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeInstances
              - ec2:DescribeSnapshots
              - ec2:DescribeTags
              - ec2:DescribeVolumes
              - ec2:DescribeVolumesModifications
              - ec2:DetachVolume
              - ec2:ModifyVolume
            Resource: "*"
      roleName: ebs-csi-driver-ap-south-1
nodeGroups:
  - name: system
    instanceType: "t3a.large"
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: a3456af4-c4de-4938-837d-86d5615d75d7
    privateNetworking: true
    amiFamily: Bottlerocket
    ami: auto-ssm
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::755502957828:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::755502957828:role/EKS-Default-SSM-AD-Role
    labels:
      workload: system
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: system
      k8s.io/cluster-autoscaler/node-template/taint/SystemAddonsOnly: NoSchedule
    taints:
      SystemAddonsOnly: "true:NoSchedule"
  - name: common
    instanceType: "t3.medium"
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: a3456af4-c4de-4938-837d-86d5615d75d7
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceProfileARN: arn:aws:iam::755502957828:instance-profile/EKS-Default-SSM-AD-Role-ip
      instanceRoleARN: arn:aws:iam::755502957828:role/EKS-Default-SSM-AD-Role
    labels:
      workload: public
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: public


fargateProfiles:
  - name: coredns
    selectors:
      - namespace: kube-system
        labels:
          eks.amazonaws.com/component: coredns
          k8s-app: kube-dns
  - name: kube-downscaler
    selectors:
      - namespace: kube-system
        labels:
          application: kube-downscaler

cloudWatch:
  clusterLogging:
    enableTypes: [ "authenticator" ]

addons:
  - name: vpc-cni
