apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: loadtester
  namespace: linkerd
spec:
  targetNamespace: apps
  interval: 1m
  path: "./kustomize/tester/"
  prune: true
  serviceAccountName: devops
  sourceRef:
    kind: GitRepository
    name: flagger
    namespace: linkerd
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger-loadtester
      namespace: apps