apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-ha
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nsl-keyclock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-ha
subjects:
  - kind: ServiceAccount
    name: default #binding to default since operator doesn't support service account
    namespace: scaling
