apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  ref:
    branch: services
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: devops
  namespace: flux-system
spec:
  path: ./overlays/us-east-1
  patchesStrategicMerge:
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    kind: Kustomization
    metadata:
      name: kube-system
      namespace: kube-system
    spec:
      postBuild:
        substitute:
          cluster_region: "us-east-1"
          account_id: "832807087073"
          env: "services"