---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: ava-nlg
    istio-injection: enabled
  name: ava-nlg

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: ava-nlg
  name: ava-nlg
  namespace: ava-nlg

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: ava-nlg
  name: ava-nlg-reconciler
  namespace: ava-nlg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:ava-nlg:reconciler
- kind: ServiceAccount
  name: ava-nlg
  namespace: ava-nlg
---
apiVersion: v1
data:
  password: Z2hwX1FIWDYzV29TRzJrdk5zOUV5TDJ0OHMyZ3Z0QnFVbjAzOXRpZg==
  username: Z2l0
kind: Secret
metadata:
  name: ava-nlg
  namespace: ava-nlg
type: Opaque
