apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-environment
  namespace: ava-nlg
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: params
    kind: ClusterSecretStore
  target:
    name: aws-environment
    creationPolicy: Merge
  data:
  - secretKey: SG
    remoteRef:
      key: /dev/secgroupid
  - secretKey: cluster_region
    remoteRef:
      key: /devops/env/zone