apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: avanlg
  namespace: avanlg
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: avanlg
  url: https://github.com/nslhb/gitops-avanlg.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: avanlg
  namespace: avanlg
spec:
  interval: 1m
  path: ./
  prune: true
  serviceAccountName: avanlg
  sourceRef:
    kind: GitRepository
    name: avanlg
  validation: client