apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod
  region: ap-south-1
  version: "1.20"

vpc:
  id: "vpc-082e04294c9380fe9"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    public:
      ap-south-1a:
        id: "subnet-093de4c9c0df7aa06"
#        cidr: "10.100.0.0/19"
      ap-south-1b:
        id: "subnet-0f11661aa8337a066"
#        cidr: "10.100.64.0/19"
#      ap-south-1c:
#        id: "subnet-014228877d6c932a6"
#        cidr: "10.100.128.0/19"
    private:
      ap-south-1a:
        id: "subnet-009a3d4c0147e8e0c"
#        cidr: "10.100.216.0/21"
      ap-south-1b:
        id: "subnet-000e508c6619a9f97"
#        cidr: "10.100.224.0/21"
#      ap-south-1c:
#        id: "subnet-0ca9b2d007b987baf"
#        cidr: "10.100.232.0/21"
iam:
  withOIDC: true
  fargatePodExecutionRolePermissionsBoundary: arn:aws:iam::901688089596:policy/Default-Boundary-Policy
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      roleName: load-balancer-ap-south-1
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      roleName: external-dns-ap-south-1
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      roleName: cluster-autoscaler-ap-south-1
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: ebs-csi-driver
        namespace: kube-system
      roleName: ebs-csi-driver-ap-south-1
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: terraform-sync-workspace
        namespace: kube-system
      roleName: terraform
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
managedNodeGroups:
  - name: system-120-0
    instanceType: "a1.xlarge"
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: ef15819c-c086-4aba-9430-d54af36d8b53
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceRoleARN: arn:aws:iam::901688089596:role/EKS-Default-SSM-AD-Role
    labels:
      workload: system
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: system
      k8s.io/cluster-autoscaler/node-template/taint/CriticalAddonsOnly: NoSchedule
    taints:
      - key: "CriticalAddonsOnly"
        value: "true"
        effect: "NoSchedule"
  - name: monitoring-120-0
    instanceType: r6g.xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: ef15819c-c086-4aba-9430-d54af36d8b53
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceRoleARN: arn:aws:iam::901688089596:role/EKS-Default-SSM-AD-Role
    labels:
      workload: monitoring
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: monitoring
      k8s.io/cluster-autoscaler/node-template/taint/monitoring: NoSchedule
    taints:
      - key: "monitoring"
        value: "true"
        effect: "NoSchedule"
  - name: tf-120-0
    instanceType: m5.4xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp3
    volumeSize: 10
    volumeEncrypted: true
    volumeKmsKeyID: ef15819c-c086-4aba-9430-d54af36d8b53
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceRoleARN: arn:aws:iam::901688089596:role/EKS-Default-SSM-AD-Role
    labels:
      part-of: Linkerd
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/part-of: Linkerd
      k8s.io/cluster-autoscaler/node-template/taint/linkerd: NoSchedule
    taints:
      - key: "tf"
        value: "true"
        effect: "NoSchedule"
  - name: paas-120-0
    instanceType: m5.4xlarge
    desiredCapacity: 3
    minSize: 0
    maxSize: 20
    volumeType: gp3
    volumeSize: 50
    volumeEncrypted: true
    volumeKmsKeyID: ef15819c-c086-4aba-9430-d54af36d8b53
    privateNetworking: true
    amiFamily: Bottlerocket
    disableIMDSv1: true
    iam:
      instanceRoleARN: arn:aws:iam::901688089596:role/EKS-Default-SSM-AD-Role
    labels:
      workload: public
      eks.amazonaws.com/compute-type: ec2
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/services: "owned"
      k8s.io/cluster-autoscaler/node-template/label/workload: public
    taints:
      - key: "paas"
        value: "true"
        effect: "NoSchedule"

cloudWatch:
  clusterLogging:
    enableTypes: [ "authenticator" ]

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

gitops:
  flux:
    gitProvider: github
    flags:
      owner: nslhb
      repository: services.nslhub.com
      branch: main
      namespace: flux-system
      path: clusters/prod/ap-south-1
      toleration-keys: CriticalAddonsOnly
      components-extra: "image-reflector-controller,image-automation-controller"
