apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - args:
            - --source=service
            - --source=ingress
            - --registry=txt
            - --provider=aws
      tolerations:
        - key: SystemAddonsOnly
          operator: Exists