apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - args:
            - --source=service
            - --source=ingress
            - --registry=txt
            - --provider=aws
            - --txtPrefix=${cluster_region}
          name: external-dns
      tolerations:
        - key: SystemAddonsOnly
          operator: Exists
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::832807087073:role/external-dns-${cluster_region}"