apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  images:
    - name: argoproj/rollouts-demo
      newName: ghcr.io/nslhb/rollouts-demo
      newTag: yellow #  {"$imagepolicy": "apps:rollouts-demo:tag"}
  patchesStrategicMerge:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: rollouts-demo-ingress
        namespace: apps
        annotations:
          external-dns.alpha.kubernetes.io/aws-region: us-east-1
          external-dns.alpha.kubernetes.io/set-identifier: us-east-1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  values:
    image:
      repository: directxman12/k8s-prometheus-adapter-arm64
      tag: v0.8.4