apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  images:
    - name: argoproj/rollouts-demo
      newName: 832807087073.dkr.ecr.ap-south-1.amazonaws.com/rollouts-demo
      newTag: green # {"$imagepolicy": "apps:rollouts-demo:tag"}
  patchesStrategicMerge:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: rollouts-demo-ingress
        namespace: apps
        annotations:
          external-dns.alpha.kubernetes.io/aws-region: us-east-1
          external-dns.alpha.kubernetes.io/set-identifier: us-east-1
