apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  images:
    - name: public.ecr.aws/bitnami/cluster-autoscaler
      newName: k8s.gcr.io/autoscaling/cluster-autoscaler-arm64
  postBuild:
    substitute:
      cluster_region: "us-east-1"
      account_id: "832807087073"
      cluster_name: "services"