apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  patchesStrategicMerge:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    spec:
      values:
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::832807087073:role/load-balancer-us-east-1
        image:
          repository: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-load-balancer-controller
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::832807087073:role/cluster-autoscaler-us-east-1
      name: cluster-autoscaler
      namespace: kube-system

