apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  postBuild:
    substitute:
      cluster_region: "ap-south-1"
      account_id: "755502957828"