apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: rollouts-demo
  namespace: apps
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollouts-demo
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: rollouts-demo
  progressDeadlineSeconds: 300
  service:
    port: 80
    targetPort: 8080
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.apps.svc.cluster.local/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl http://roullouts-demo-canary/color"
      - name: load-test
        type: rollout
        url: http://flagger-loadtester.apps.svc.cluster.local/
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 http://roullouts-demo-canary/color"