name: e2e

on:
  workflow_dispatch:
  pull_request:
    paths:
      - clusters/dev/ap-south-1/flux-system/*
      - policy/kyverno/*

jobs:
  kubernetes:
#    strategy:
#      matrix:
#        arch: [ ["ubuntu-latest"], ["self-hosted", "linux", "ARM64"] ]
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
      - name: Install Flux in Kubernetes Kind
        run: flux install
      - run: echo clusters/dev/tenants.yaml > .sourceignore
      - name: Setup cluster reconciliation
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/}
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./clusters/dev/ap-south-1
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
          kubectl -n flux-system wait kustomization/kyverno-policies --for=condition=ready --timeout=1m
          kubectl -n flux-system wait kustomization/flux-system --for=condition=ready --timeout=1m
#      - name: Verify tenant reconciliation
#        run: |
#          kubectl -n apps wait helmrelease/podinfo --for=condition=ready --timeout=1m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          kubectl -n kyverno get all
          kubectl -n kyverno logs deploy/kyverno
