name: e2e

on:
  workflow_dispatch:
  pull_request:
    paths:
      - clusters/dev/ap-south-1/flux-system/*
      - policy/kyverno/*

jobs:
  kubernetes:
    strategy:
      matrix:
        runner: [ [ "ubuntu-latest" ], [ "self-hosted", "linux", "ARM64" ] ]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flux
        uses: ./.github/actions/flux
      - name: Setup Kubernetes
        uses: nslhb/kind-action@main
      - name: Install Flux in Kubernetes Kind
        run: flux install --components-extra=image-reflector-controller,image-automation-controller
      - run: |
          flux create source git flux-system --url=${{ github.event.repository.html_url }} --branch=${{ github.head_ref }}
          flux reconcile source git flux-system -n flux-system
      - name: Setup kyverno reconciliation
        run: flux create kustomization kyverno --source=flux-system --path=./policy/kyverno --health-check="Deployment/kyverno.kyverno"
      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/flux-system --for=condition=ready --timeout=1m
          kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          kubectl -n kyverno get all
          kubectl -n kyverno logs deploy/kyverno