name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  kyverno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Fetch kyverno latest version
        id: version
        run: |
          REPO="https://github.com/kyverno/kyverno.git"
          VERSION=$(cd /tmp && git ls-remote --tags --refs --sort='version:refname' ${REPO} | \
          sed 's/.*\///' | \
          awk '{ if ($1 ~ /-/) print; else print $0"_" ; }' | \
          sort -rV | \
          sed 's/_$//' | \
          head -n1)
          echo ::set-output name=NUMBER::${VERSION}
      - name: Patch version
        run: |
          export URL="https://raw.githubusercontent.com/kyverno/kyverno/${{ steps.version.outputs.NUMBER }}/definitions/release/install.yaml"
          yq e '.resources[0]=strenv(URL)' -i policy/kyverno/kustomization.yaml
      - name: Check for flux updates
        id: update
        run: |
          flux install --toleration-keys=CriticalAddonsOnly --components-extra=image-reflector-controller,image-automation-controller --export > ./clusters/dev/ap-south-1/flux-system/gotk-components.yaml
          flux install --toleration-keys=CriticalAddonsOnly --components-extra=image-reflector-controller,image-automation-controller --export > ./clusters/e2e/flux-system/gotk-components.yaml
          flux install --toleration-keys=CriticalAddonsOnly --components-extra=image-reflector-controller,image-automation-controller --export > ./clusters/services/ap-south-1/flux-system/gotk-components.yaml
          flux install --toleration-keys=CriticalAddonsOnly --components-extra=image-reflector-controller,image-automation-controller --export > ./clusters/services/us-east-1/flux-system/gotk-components.yaml
          VERSION="$(flux -v)"
          echo "::set-output name=flux_version::$VERSION"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-system
          committer: GitHub <noreply@github.com>
          author: fluxcdbot <fluxcdbot@users.noreply.github.com>
          signoff: true
          commit-message: auto update
          title: Update flux ${{ steps.update.outputs.flux_version }}/ kyverno ${{ steps.version.outputs.NUMBER }}
          body: |
            flux ${{ steps.update.outputs.flux_version }}
            kyverno ${{ steps.version.outputs.NUMBER }}